config/routes.rb
Bedside::Application.routes.draw do

  authenticated :user do
    root :to => 'home#index'
  end
  root :to => "home#index"

  devise_for :users do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end

  resources :users
  resources :pages do
    resources :wishes, :posts, :page_participations, :visits, :comments
  end
end

app/views/pages/_comments.html.haml
%i.icon.icon-comments.pull-left.icon-4
%h4.heading.lower-heading
  Discussion Board
%br/
= simple_form_for([@page, Comment.new], :remote => true, :html => {:class => 'form-vertical' }) do |f|
  = f.input :body, as: "text", :placeholder => "Say something!", :input_html => { :class => 'textarea' }, label: false

  =f.button :submit, "Post", :class => "btn btn-mini btn-3"

- @page.comment_threads.reverse.each  do |comment|
  .well
    = comment.body
  %p
    by #{comment.user.name}
    (#{comment.created_at.strftime("%m/%d/%Y at %I:%M%p")})

  %br

app/views/pages/_location.html.haml
- if @page.can_edit?(current_user)
  %button.btn.btn-mini.pull-right{"data-attribute" => "location", "data-type" => "edit-button"} Edit
%h4.heading.heading-1
  Location
  %br/
.location-container
  -if !@page.hospital.blank?
    Hospital
    %p.info-text
      #{@page.hospital}
      %br/
  -elsif @page.can_edit?(current_user)
    %p
      Add hospital info
  -if !@page.room.blank?
    Room
    %p.info-text
      #{@page.room}
      %br/
  -elsif @page.can_edit?(current_user)
    %p
      Add room number
  -if !@page.visiting_hours.blank?
    Visiting hours
    #{simple_format(@page.visiting_hours, class: "info-text")}
  -elsif @page.can_edit?(current_user)
    %p
      Add visiting hours
.location-editable-container.hidden
  = form_for @page, remote: true, html: {id: "location-edit-form"} do |f|
    %p
      %br
      = f.text_field :hospital, placeholder: "hospital"
      %br
      = f.text_field :room, placeholder: "room"
      %br
      = f.text_area :visiting_hours, placeholder: "Visiting hours:\n e.g. \n Weekdays: 9 AM - 9 PM\n Weekends: 11AM - 5PM"
    %button.btn{"data-attribute" => "location", "data-type" => "cancel-button"}
      Cancel
    = f.submit"Save", class: "btn btn-primary", "data-attribute" => "location", "data-type" => "save-button"

app/views/pages/_overview.html.haml
- if @page.can_edit?(current_user)
  %button.btn.btn-mini.pull-right{"data-attribute" => "overview", "data-type" => "edit-button"} Edit
%h4.heading.heading-1
  How's #{@page.patient_name} doing?
  %br/
.overview-container
  -if !@page.overview.blank?
    %p
      #{simple_format(@page.overview, class: "info-text")}
  -elsif @page.can_edit?(current_user)
    %p
      Add some general info about the patient's condition.
    %p
      You'll be able to post updates below as the situation changes.

.overview-editable-container.hidden
  = form_for @page, remote: true, html: {id: "overview-edit-form"} do |f|
    %p
      = f.text_area :overview, placeholder: "Add some general info about Susan's condition."
      %br
      %button.btn{"data-attribute" => "overview", "data-type" => "cancel-button"}
        Cancel
      = f.submit"Save", class: "btn btn-primary", "data-attribute" => "overview", "data-type" => "save-button"

app/views/pages/_photo.html.haml
#patient-photo
  -if @page.avatar_url
    =filepicker_image_tag @page.avatar_url, w: 160, h: 160, fit: 'clip'
  -else
    %img{src: "/assets/no-profile-image.jpeg"}
  - if @page.can_edit?(current_user)
    #upload-form
      = simple_form_for @page do |f|
        -if @page.avatar_url
          =f.filepicker_field :avatar_url, button_text: "Change photo", button_class:"btn", onchange: 'window.Bedside.updatePhoto(event);' 
        -else
          =f.filepicker_field :avatar_url, button_text: "Upload a photo", button_class:"btn", onchange: 'window.Bedside.updatePhoto(event);'

app/views/pages/_posts.html.haml
%i.icon.icon-bullhorn.pull-left.icon-3
%h4.heading.lower-heading
  Latest Update
  %br/
%p
  - if @page.posts.empty?
    No updates yet.
  -else
    .well
      %p
        #{simple_format(@page.posts.last.body, class: "info-text")}
    %p
      Posted on
      = @page.posts.last.created_at.strftime("%m/%d/%Y at %I:%M%p")


- if @page.can_edit?(current_user)
  = simple_form_for([@page, Post.new], :remote => true, :html => {:class => 'form-vertical' }) do |f|
    = f.input :body, as: "text", :placeholder => "Provide an update on #{@page.patient_name.possessive} condition", :input_html => { :class => 'textarea' }, label: false
    = f.input :user_id, as: :hidden, input_html: {value: current_user.id}

    =f.button :submit, "Update", :class => "btn btn-mini btn-3"

app/views/pages/_tips.html.haml
- if @page.can_edit?(current_user)
  %button.btn.btn-mini.pull-right{"data-attribute" => "tips", "data-type" => "edit-button"} Edit
%h4.heading.heading-1
  Visitor's Tips
  %br/
.tips-container
  - if !@page.tips.blank?
    #{simple_format(@page.tips, class: "info-text")}
  -elsif @page.can_edit?(current_user)
    %p
      Add some tips for visitors.
    %p
      (Suggestions: Parking hints, treats the nurses like, conversation topics, etc)

.tips-editable-container.hidden
  = form_for @page, remote: true, html: {id: "tips-edit-form"} do |f|
    %p
      = f.text_area :tips, placeholder: "(Suggestions: Parking hints, treats the nurses like, conversation topics, etc)"
      %br
    %button.btn{"data-attribute" => "tips", "data-type" => "cancel-button"}
      Cancel
    = f.submit"Save", class: "btn btn-primary", "data-attribute" => "tips", "data-type" => "save-button"

app/views/pages/_visits.html.haml
%i.icon.icon-calendar.pull-left.icon-1
%h4.heading.lower-heading
  Visitor Schedule
.inner-container
  -@schedule.each do |k,day|
    %table.table.table-striped.table-condensed
      %thead
        %tr
          %th
            =day[:date].strftime('%A, %b %e')
            =link_to 'Add yourself', "/pages/#{@page.id}/visits/new?day=#{k}", {:remote => true, :class => "btn btn-mini pull-right", :id => 'add_page_wish'}
      -if !day[:visits].blank?
        %tbody
          -day[:visits].each do |v|
            %tr
              %td
                #{v.start_hour} - #{v.user.name}
                - if v.user_id == current_user.id or @page.can_edit?(current_user)
                  %span.pull-right
                    =link_to 'cancel', "/pages/#{@page.id}/visits/#{v.id}", {:remote => true, :method => "delete", :class => "pull-right", :confirm => "Are you sure that you want to cancel this visit?"}

app/views/pages/_wishlist.html.haml
%i.icon.icon-gift.pull-left.icon-2
=link_to 'Add Item', "/pages/#{@page.id}/wishes/new", {:remote => true, :class => "btn btn-mini pull-right btn-1", :id => 'add_page_wish'} if @page.can_edit?(current_user)


%h4.heading.lower-heading
  Wishlist
.inner-container
  %table.table.table-striped.table-condensed
    %tbody
      -@page.wishes.each do |wish|
        %tr
          %td.wish
            - if @page.can_edit?(current_user)
              %span.pull-right
                =link_to 'remove', "/pages/#{@page.id}/wishes/#{wish.id}", {:remote => true, :method => "delete", :class => "pull-right", :confirm => "Are you sure that you want to remove this wish?"}
            =simple_form_for [@page,wish], :remote => true do |f|
              =f.input :claimed, :label => wish.title, :inline_label => true
              -if wish.claimed_by
                .claimed
                  Claimed by #{wish.user.name}
              

app/views/pages/new.html.haml
.full-image-bg
  #getting-started-form
    %h1.heading
      Great!
      %br
    .dom-body-text
      %p.p-1 Now, let's create a Bedside page. 
      %p.p-1 This page will be the place where family, friends, and visitors get info and updates.
    = simple_form_for(@page, :html => {:class => 'form-vertical' }) do |f|
      = f.error_notification
      = f.input :patient_name, :autofocus => true
      = f.input :hospital, :label => 'Hospital'
      = f.input :room
      = f.input :visiting_hours
      = f.button :submit, 'Create Page', :class => 'btn-primary'
  %br/

app/views/pages/show.html.haml
#page-container
  .navbar.navbar-inverse
    .navbar-inner
      %a.brand{:href => "#{root_url}"}
        %b Bedside
      %ul.nav
        %li.dropdown
          %a.dropdown-toggle{:href => "#", "data-toggle" => "dropdown"}
            My Pages
            %b.caret
          %ul.dropdown-menu
            - current_user.pages.each do |page|
              %li
                = link_to "#{page.patient_name}", page_path(page)

        %li.dropdown
          %a.dropdown-toggle{:href => "#", "data-toggle" => "dropdown"}
            Options
            %b.caret
          %ul.dropdown-menu
            %li
              = link_to "Create New Page", new_page_path
            %li
              =link_to 'Account Settings', "#{edit_user_path(current_user)}", {:remote => true, :id => 'edit_user'}
            %li
              = link_to 'Logout', destroy_user_session_path, :method=>'delete'
      .pull-right.nav.welcome
        Welcome to Bedside #{current_user.name} !

  .container-fluid.page-title-bar
    .row-fluid
      %span.span12
        %h1.heading
          #{@page.patient_name.possessive} Bedside Page
          =link_to 'Invite people', "/pages/#{@page.id}/page_participations", {:remote => true, :class => "btn btn-primary pull-right", :id => 'add_page_participation'} if @page.can_edit?(current_user)
  .container-fluid.main-info
    .row-fluid
      %span.span4
        =render "photo"
      %span.span4
        #location-partial-container.detials-partial-container
          =render "location"
        #tips-partial-container.detials-partial-container
          =render "tips"

      %span.span4
        #overview-partial-container.detials-partial-container
          =render "overview"
  .container-fluid.lower-container
    .row-fluid
      %span.span4
        #visits
          =render "visits"
        #wishlist
          =render "wishlist"

      %span.span8
        #posts
          =render "posts"
        #comments
          =render "comments"
  #pageModal

app/views/pages/unauthorized.html.haml
.full-image-bg
  #getting-started-form
    %center
      %h3.heading
        Unauthorized Access
        %br
      .dom-body-text
        %p.p-1 Sorry, your account does not have access to this Bedside page.

  %br/

app/views/pages/update.js.haml
//re-render only the sections that were updated when a Page was updated.
-if ["room","hospital","visiting_hours"].any?{|k| @page.previous_changes.keys.include?(k)}
  $("#location-partial-container").html("#{escape_javascript(render 'location')}");

-if ["tips"].any?{|k| @page.previous_changes.keys.include?(k)}
  $("#tips-partial-container").html("#{escape_javascript(render 'tips')}");

-if ["overview"].any?{|k| @page.previous_changes.keys.include?(k)}
  $("#overview-partial-container").html("#{escape_javascript(render 'overview')}");